import arcade
from arcade import load_texture
from arcade.gui import UIManager
from arcade.gui.widgets import UITextArea, UIInputText, UITexturePane



LOREM_IPSUM = (
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
        "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
 
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
   
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
"sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"

    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
        "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
     
"sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
        "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
        "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "sfdgncxgfds"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "fdgcgdffgxfz"
    "dsfgxhhdzdg"
    "fdxzsdfxzdxx"
    "\n"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"
    "DSzfxgxdffgd"
    "dfxgdfgdgfd"


)

class MyWindow(arcade.Window):
    def __init__(self):
        super().__init__(800, 600, "Scrollable Text", resizable=True)
        self.manager = UIManager()
        self.manager.enable()
        arcade.set_background_color(arcade.color.DARK_YELLOW)

        bg_tex = load_texture(":resources:gui_basic_assets/window/grey_panel.png")
        text_area = UITextArea(x=100,
                               y=100,
                               width=200,
                               height=500,
                               text=LOREM_IPSUM,
                               text_color=(0, 0, 0, 15))

        self.manager.add(
            UITexturePane(
                text_area.with_space_around(right=20),
                tex=bg_tex,
                padding = (10,10,10,10)
            )
        )

        self.manager.add(
            UITexturePane(
                UIInputText(x=340, y=200, width=200, height=50, text="Hello"),
                tex=bg_tex,
                padding = (10,10,10,10)
        ))

        self.manager.add(
            UIInputText(x=340, y=110, width=200, text='Hello'),
        )

    def on_draw(self):
        self.clear()
        self.manager.draw()

window = MyWindow()
arcade.run()